import type { SpeedCamera } from "./types";

export const cameras: SpeedCamera[] = [
  {
    id: "cam-nz-001",
    type: "fixed",
    status: "active",
    location: { lat: -36.8663, lng: 174.7758 },
    road: "SH1 - Auckland Harbour Bridge",
    region: "Auckland",
    speed_limit: 80,
  },
  {
    id: "cam-nz-002",
    type: "fixed",
    status: "active",
    location: { lat: -36.9015, lng: 174.8099 },
    road: "Great South Road, Greenlane",
    region: "Auckland",
    speed_limit: 50,
  },
  {
    id: "cam-nz-003",
    type: "average",
    status: "active",
    location: { lat: -41.2836, lng: 174.7761 },
    road: "Aotea Quay",
    region: "Wellington",
    speed_limit: 60,
  },
  {
    id: "cam-nz-004",
    type: "fixed",
    status: "inactive",
    location: { lat: -41.3168, lng: 174.7699 },
    road: "Adelaide Road, Newtown",
    region: "Wellington",
    speed_limit: 50,
  },
  {
    id: "cam-nz-005",
    type: "fixed",
    status: "active",
    location: { lat: -43.5135, lng: 172.6465 },
    road: "Linwood Ave",
    region: "Christchurch",
    speed_limit: 50,
  },
  {
    id: "cam-nz-006",
    type: "average",
    status: "active",
    location: { lat: -43.5321, lng: 172.6362 },
    road: "Moorhouse Avenue",
    region: "Christchurch",
    speed_limit: 60,
  },
  {
    id: "cam-nz-007",
    type: "fixed",
    status: "active",
    location: { lat: -36.8485, lng: 174.7633 },
    road: "Fanshawe Street",
    region: "Auckland",
    speed_limit: 50,
  },
  {
    id: "cam-nz-008",
    type: "fixed",
    status: "active",
    location: { lat: -41.2910, lng: 174.7824 },
    road: "Waterfront Drive",
    region: "Wellington",
    speed_limit: 50,
  },
  {
    id: "cam-nz-009",
    type: "inactive",
    status: "inactive",
    location: { lat: -43.5513, lng: 172.6289 },
    road: "Blenheim Road",
    region: "Christchurch",
    speed_limit: 60,
  },
  {
    id: "cam-nz-010",
    type: "average",
    status: "active",
    location: { lat: -36.7580, lng: 174.7020 },
    road: "SH1 - Northern Motorway",
    region: "Auckland",
    speed_limit: 100,
  }
];
