import type { SpeedCamera } from "./types";

export const cameras: SpeedCamera[] = [
  {
    id: "cam-001",
    type: "fixed",
    status: "active",
    location: { lat: 51.5074, lng: -0.1278 },
    road: "A4 - Trafalgar Square",
    region: "Central London",
    speed_limit: 30,
  },
  {
    id: "cam-002",
    type: "average",
    status: "active",
    location: { lat: 51.5188, lng: -0.0815 },
    road: "A10 - Shoreditch High Street",
    region: "East London",
    speed_limit: 20,
  },
  {
    id: "cam-003",
    type: "fixed",
    status: "inactive",
    location: { lat: 51.4934, lng: -0.1751 },
    road: "A4 - Cromwell Road",
    region: "West London",
    speed_limit: 40,
  },
  {
    id: "cam-004",
    type: "fixed",
    status: "active",
    location: { lat: 51.4613, lng: -0.1156 },
    road: "A23 - Brixton Hill",
    region: "South London",
    speed_limit: 30,
  },
  {
    id: "cam-005",
    type: "average",
    status: "active",
    location: { lat: 51.5560, lng: -0.2796 },
    road: "A406 - North Circular Road",
    region: "North London",
    speed_limit: 50,
  },
  {
    id: "cam-006",
    type: "fixed",
    status: "active",
    location: { lat: 51.509865, lng: -0.118092 },
    road: "A3211 - Victoria Embankment",
    region: "Central London",
    speed_limit: 30,
  },
  {
    id: "cam-007",
    type: "fixed",
    status: "active",
    location: { lat: 51.4816, lng: -0.0163 },
    road: "A200 - Evelyn Street",
    region: "South East London",
    speed_limit: 30,
  },
  {
    id: "cam-008",
    type: "inactive",
    status: "inactive",
    location: { lat: 51.5348, lng: -0.0434 },
    road: "A11 - Mile End Road",
    region: "East London",
    speed_limit: 30,
  },
  {
    id: "cam-009",
    type: "average",
    status: "active",
    location: { lat: 51.4005, lng: -0.3017 },
    road: "A3 - Kingston Bypass",
    region: "South West London",
    speed_limit: 50,
  },
  {
    id: "cam-010",
    type: "fixed",
    status: "active",
    location: { lat: 51.6033, lng: -0.1481 },
    road: "A1000 - High Road, Finchley",
    region: "North London",
    speed_limit: 30,
  },
];
